#! /bin/sh

set -e

if [ "$1" = configure ]; then
  if [ -d /usr/include/python3.4 ] && [ ! -h /usr/include/python3.4 ]; then
    if rmdir /usr/include/python3.4 2> /dev/null; then
      ln -sf python3.4mu /usr/include/python3.4
    else
      echo >&2 "WARNING: non-empty directory on upgrade: /usr/include/python3.4"
      ls -l /usr/include/python3.4
    fi
  fi
  if [ -d /usr/lib/python3.4/config ] && [ ! -h /usr/lib/python3.4/config ]; then
    if rmdir /usr/lib/python3.4/config 2> /dev/null; then
      ln -sf config-3.4mu /usr/lib/python3.4/config
    else
      echo >&2 "WARNING: non-empty directory on upgrade: /usr/lib/python3.4/config"
      ls -l /usr/lib/python3.4/config
    fi
  fi
fi



exit 0
