#!/bin/sh

set -e

case "${1}" in
  remove|deconfigure)
    update-alternatives --remove x-session-manager /usr/bin/startlxde-pi
    ;;

  upgrade|failed-upgrade)

    ;;

  *)
    echo "prerm called with unknown argument \`${1}'" >&2
    exit 1
    ;;
esac

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/90xmodmap 1.0-7 −− "$@" -- "$@"
# End automatically added section


exit 0
